- name: install epel software
  dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - epel-release
  become: true

- name: install software
  dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - fail2ban
    - bash-completion
    - yum-utils
  become: true
