- name: setup user
  user:
    name: "{{ item }}"
  with_items:
    - "{{ users }}"

- name: copy hzd demo key for awx
  ansible.posix.authorized_key:
    user: "{{ item }}"
    state: present
    key: "{{ lookup('file', 'ssh-pub-keys/hzd.pub') }}"
  with_items:
    - root
    - "{{ users }}"

- name: copy sudoers
  template:
    src: sudoers
    dest: "/etc/sudoers.d/{{ item }}"
    owner: root
    group: root
    mode: 0440
  with_items:
    - "{{ users }}"

