- import_tasks: 01_install_software.yml
  tags:
    - install_software

- import_tasks: 02_setup_users.yml
  tags:
    - setup_users
        
- import_tasks: 03_configure_fail2ban.yml
  tags:
    - fail2ban
- import_tasks: 20_systemd.yml
  tags:
    - firewall
    - fail2ban
- import_tasks: 30_firewalld.yml
  tags:
    - firewall
