---
- import_tasks: 01_install_software.yml
- import_tasks: 02_setup_users.yml  
  tags:
    - setup_users
- import_tasks: 03_fail2ban.yml 
  tags:
    - fail2ban
- import_tasks: 20_systemd.yml
  tags:
    - systemd
- import_tasks: 30_firewalld.yml
  tags:
    - firewall
